modLoader="javafml"
loaderVersion="[40,)"
license="The MIT License (MIT)"
issueTrackerURL="https://github.com/Dakuro/Arkhesys/issues"

[[mods]]
modId="arkhesys"
version="${file.jarVersion}"
displayName="Arkhesys"
updateJSONURL="https://github.com/Dakuro/Arkhesys/blob/1.18.2-Forge/update.json"
displayURL="https://github.com/Dakuro/Arkhesys"
logoFile="logo.png"
credits=""
authors="Dakuro"
description='''
!- This mod is in early stages of its development -!

Arkhesys is an original mod about sorcery, machinery, quests and journeys, all wrapped up in lore and storytelling.
It aims to provide its own "unique" feeling as much as possible, while proposing players engaging and memorable experiences.
Game design is made with players in mind, so you can both discover it entirely on your own or share it with some friends!

!- Most features are still in creation, thank you for your patience and support -!
'''

[[dependencies.arkhesys]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.arkhesys]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
